name: xplex-push-history

on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday at 00:00 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  update-push-history:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required to update README.md
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Required to get full commit history :cite[2]:cite[10]
      
      - name: Generate push history data
        run: |
          # Get push events from GitHub API and process monthly counts
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/namakshenas/xplex/events?per_page=100" | \
            jq -r '.[] | select(.type == "PushEvent") | .created_at | strptime("%Y-%m-%dT%H:%M:%SZ") | "\(.year+1900)-\(.month+1)"' | \
            sort | uniq -c | awk '{print $2 " " $1}' > monthly_pushes.txt
          
          # Generate mermaid xychart
          echo '```mermaid' > chart.md
          echo 'xychart-beta' >> chart.md
          echo '    title "xplex Monthly Push History"' >> chart.md
          echo '    x-axis ["'$(awk '{print $1}' monthly_pushes.txt | paste -sd, - | sed 's/,/", "/g')'"]' >> chart.md
          echo '    y-axis "Number of Pushes" 0 -->' $(($(awk '{print $2}' monthly_pushes.txt | sort -nr | head -n1)+1)) >> chart.md
          echo '    bar ['$(awk '{print $2}' monthly_pushes.txt | paste -sd, -)']' >> chart.md
          echo '```' >> chart.md
      
      - name: Update README with new chart
        run: |
          # Replace content between the markers with the new chart
          sed -i '/<!-- XPLEX-PUSH-HISTORY-START -->/,/<!-- XPLEX-PUSH-HISTORY-END -->/{
            /<!-- XPLEX-PUSH-HISTORY-START -->/{
              r chart.md
            }
            /<!-- XPLEX-PUSH-HISTORY-END -->/!d
          }' README.md
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update xplex push history chart [automated]"
          git push
