name: xplex-push-history

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout profile repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        
    - name: Checkout xplex repo
      uses: actions/checkout@v4
      with:
        repository: namakshenas/xplex
        path: xplex
        token: ${{ secrets.PAT }}
        fetch-depth: 0
        
    - name: Generate chart and update README
      run: |
        cd xplex
        
        # Get ALL monthly commit counts from complete history
        git log --date=format:'%Y-%m' --pretty=format:'%ad' | sort | uniq -c | sort -k2 > ../commits.txt
        
        cd ..
        
        # Build the chart
        echo '<!-- XPLEX-PUSH-HISTORY-START -->' > chart.md
        echo '' >> chart.md
        echo '```mermaid' >> chart.md
        echo 'xychart' >> chart.md
        echo '  title "xplex history!"' >> chart.md
        echo -n '  x-axis [' >> chart.md
        awk '{printf "\"%s\", ", $2}' commits.txt | sed 's/, $//' >> chart.md
        echo ']' >> chart.md
        echo '  y-axis "Commits"' >> chart.md
        echo -n '  bar [' >> chart.md
        awk '{printf "%s, ", $1}' commits.txt | sed 's/, $//' >> chart.md
        echo ']' >> chart.md
        echo -n '  line [' >> chart.md
        awk '{printf "%s, ", $1}' commits.txt | sed 's/, $//' >> chart.md
        echo ']' >> chart.md
        echo '```' >> chart.md
        echo '' >> chart.md
        echo '<!-- XPLEX-PUSH-HISTORY-END -->' >> chart.md
        
        # Replace section in README
        awk '
          /<!-- XPLEX-PUSH-HISTORY-START -->/ {f=1}
          !f {print}
          /<!-- XPLEX-PUSH-HISTORY-END -->/ {system("cat chart.md"); f=0}
        ' README.md > README.tmp && mv README.tmp README.md
        
        rm commits.txt chart.md
        
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update xplex commit history" && git push)