name: xplex-push-history

on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday at 00:00 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  update-push-history:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history
      
      - name: Generate push history data
        run: |
          # Get push events from GitHub API with better error handling
          response=$(curl -s -w "\n%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/namakshenas/xplex/events?per_page=100")
          
          http_code=$(echo "$response" | tail -n1)
          json_data=$(echo "$response" | sed '$d')
          
          if [ "$http_code" != "200" ]; then
            echo "API request failed with HTTP $http_code"
            echo "Response: $json_data"
            # Fallback to empty data
            echo '' > monthly_pushes.txt
          else
            # Process JSON data with proper error handling
            echo "$json_data" | jq -r '
              if type == "array" then
                .[] | select(type == "object" and has("type")) | select(.type == "PushEvent") | .created_at
              else
                empty
              end' | \
            awk -F'T' '{print $1}' | awk -F'-' '{print $1"-"$2}' | \
            sort | uniq -c | awk '{print $2 " " $1}' > monthly_pushes.txt
          fi
          
          # Check if we have data
          if [ ! -s monthly_pushes.txt ]; then
            echo "No push events found. Using default message."
            echo '```mermaid' > chart.md
            echo 'xychart-beta' >> chart.md
            echo '    title "xplex Monthly Push History"' >> chart.md
            echo '    x-axis ["No Data"]' >> chart.md
            echo '    y-axis "Number of Pushes" 0 --> 5' >> chart.md
            echo '    bar [0]' >> chart.md
            echo '```' >> chart.md
          else
            # Generate mermaid xychart with proper formatting
            echo '```mermaid' > chart.md
            echo 'xychart-beta' >> chart.md
            echo '    title "xplex Monthly Push History"' >> chart.md
            
            # Format x-axis labels correctly
            x_labels=$(awk '{printf "\"%s\", ", $1}' monthly_pushes.txt | sed 's/, $//')
            if [ -z "$x_labels" ]; then
              x_labels='"No Data"'
            fi
            echo "    x-axis [$x_labels]" >> chart.md
            
            # Format y-axis with proper range
            max_value=$(awk '{print $2}' monthly_pushes.txt | sort -nr | head -n1)
            y_max=$((max_value + 1))
            echo "    y-axis \"Number of Pushes\" 0 --> $y_max" >> chart.md
            
            # Format bar data correctly
            bar_data=$(awk '{printf "%s, ", $2}' monthly_pushes.txt | sed 's/, $//')
            if [ -z "$bar_data" ]; then
              bar_data='0'
            fi
            echo "    bar [$bar_data]" >> chart.md
            echo '```' >> chart.md
          fi
      
      - name: Update README with new chart
        run: |
          # Create temporary file with start marker and chart
          echo '<!-- XPLEX-PUSH-HISTORY-START -->' > temp.md
          cat chart.md >> temp.md
          echo '<!-- XPLEX-PUSH-HISTORY-END -->' >> temp.md
          
          # Extract content before and after the markers
          sed -n '1,/<!-- XPLEX-PUSH-HISTORY-START -->/p' README.md | head -n -1 > before.md
          sed -n '/<!-- XPLEX-PUSH-HISTORY-END -->/,$p' README.md | tail -n +2 > after.md
          
          # Combine all parts
          cat before.md temp.md after.md > README_new.md
          mv README_new.md README.md
          
          # Clean up
          rm -f temp.md before.md after.md chart.md monthly_pushes.txt
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Update xplex push history chart [automated]"
          git push
