name: xplex-push-history

on:
  schedule:
    - cron: "0 0 * * 5" # every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout xplex repo
        uses: actions/checkout@v4
        with:
          repository: namakshenas/xplex
          path: xplex
          fetch-depth: 0

      - name: Generate commit history chart
        run: |
          cd xplex
          commits=$(git log --date=format:'%Y-%m' --pretty='%ad' | sort | uniq -c)
          months=$(echo "$commits" | awk '{print $2}' | xargs | sed 's/ /, /g')
          counts=$(echo "$commits" | awk '{print $1}' | xargs | sed 's/ /, /g')

          chart="\`\`\`mermaid
          xychart-beta
              title: XPLEX Monthly Commits
              x-axis [$months]
              y-axis Commits
              line [$counts]
          \`\`\`"

          cd ..
          tmpfile=$(mktemp)
          awk -v chart="$chart" '
            /<!-- XPLEX-PUSH-HISTORY-START -->/ { print; print chart; found=1; next }
            /<!-- XPLEX-PUSH-HISTORY-END -->/ { found=0 }
            !found { print }
          ' README.md > "$tmpfile"
          mv "$tmpfile" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update XPLEX push history chart" || echo "No changes to commit"
          git push
