name: xplex-push-history

on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday at 00:00 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  update-push-history:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history:cite[1]
      
      - name: Generate push history data
        run: |
          # Get push events from GitHub API
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/namakshenas/xplex/events?per_page=100" | \
            jq -r '.[] | select(.type == "PushEvent") | .created_at | sub("T.*"; "") | sub("-[0-9]{2}$"; "")' | \
            sort | uniq -c | awk '{print $2 " " $1}' > monthly_pushes.txt
          
          # Generate mermaid xychart with proper formatting
          echo '```mermaid' > chart.md
          echo 'xychart-beta' >> chart.md
          echo '    title "xplex Monthly Push History"' >> chart.md
          
          # Format x-axis labels correctly
          x_labels=$(awk '{printf "\"%s\", ", $1}' monthly_pushes.txt | sed 's/, $//')
          echo "    x-axis [$x_labels]" >> chart.md
          
          # Format y-axis with proper range
          max_value=$(awk '{print $2}' monthly_pushes.txt | sort -nr | head -n1)
          y_max=$((max_value + 1))
          echo "    y-axis \"Number of Pushes\" 0 --> $y_max" >> chart.md
          
          # Format bar data correctly
          bar_data=$(awk '{printf "%s, ", $2}' monthly_pushes.txt | sed 's/, $//')
          echo "    bar [$bar_data]" >> chart.md
          echo '```' >> chart.md
      
      - name: Update README with new chart
        run: |
          # Create temporary marker pattern for replacement
          sed -i '/<!-- XPLEX-PUSH-HISTORY-START -->/,/<!-- XPLEX-PUSH-HISTORY-END -->/{
            /<!-- XPLEX-PUSH-HISTORY-START -->/{
              n
              r chart.md
            }
            /<!-- XPLEX-PUSH-HISTORY-END -->/!d
          }' README.md
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Update xplex push history chart [automated]"
          git push
