name: xplex-push-history

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout profile repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        
    - name: Checkout xplex repo
      uses: actions/checkout@v4
      with:
        repository: namakshenas/xplex
        path: xplex
        token: ${{ secrets.PAT }}
        fetch-depth: 0
        
    - name: Generate chart and update README
      run: |
        cd xplex
        
        # Get monthly commit counts
        data=$(git log --format="%Y-%m" | sort | uniq -c | sort -k2 | tail -12 | awk '{print "[\""$2"\", "$1"]"}' | tr '\n' ',' | sed 's/,$//')
        
        # Generate Mermaid chart
        chart="---
        config:
          themeVariables:
            xyChart:
              backgroundColor: \"transparent\"
        ---
        %%{init: {'theme':'dark'}}%%
        xychart-beta
          title \"xplex Monthly Commits\"
          x-axis [$(echo "$data" | sed 's/\["\([^"]*\)",[^]]*\]/\1/g' | tr ',' ' ')]
          y-axis \"Commits\"
          bar [$(echo "$data" | sed 's/\["[^"]*", \([0-9]*\)\]/\1/g' | tr ',' ' ')]"
        
        # Update README
        cd ..
        sed -i "/<!-- XPLEX-PUSH-HISTORY-START -->/,/<!-- XPLEX-PUSH-HISTORY-END -->/c\<!-- XPLEX-PUSH-HISTORY-START -->\n\n\`\`\`mermaid\n$chart\n\`\`\`\n\n<!-- XPLEX-PUSH-HISTORY-END -->" README.md
        
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update xplex commit history" && git push)